# Generated by Django 3.0.5 on 2020-07-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='images',
        ),
        migrations.AddField(
            model_name='data',
            name='images',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
