# Generated by Django 3.0.5 on 2020-07-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200730_0652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
    ]
