# Generated by Django 3.0.5 on 2020-08-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(upload_to='img/file1/')),
                ('file2', models.FileField(upload_to='img/file2/')),
                ('file3', models.FileField(upload_to='img/file3/')),
                ('file4', models.FileField(upload_to='img/file4/')),
                ('file5', models.FileField(upload_to='img/file5/')),
                ('file6', models.FileField(upload_to='img/file6/')),
            ],
        ),
    ]
